### ISSUE TITLE
DocBook 5.1 catalog.xml uses incorrect version

### ISSUE THREAD

**Issue by bobstayton** [docbook/docbook#100]
The catalog.xml file that is one of the work products of the DocBook v5.1 OASIS Standard uses the wrong version in its name attributes.  For example:
name="http://docbook.org/xml/5.1CR4/rng/docbook.rng"
The "CR4" should not be included.  

Because the catalog.xml file is one of the work products included with the Standard, the correction for this must be approved as an Errata to the Standard.

**Comment by ndw** [comment]
I believe we fixed this.
