### ISSUE TITLE
Add "interface" value to systemitem class

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#102]
From the thread on the [docbook mailinglist](https://lists.oasis-open.org/archives/docbook/201804/msg00001.html), subject "Which DocBook element to use for NICs?"

Request:
Adding the value `interface` to the `class` attribute of element `systemitem`.

Probably needs to be added in `db.systemitem.class.enumeration`.

**Comment by kosek** [comment]
Implemented in 5.2b05
Schema is available for testing at https://docbook.org/xml/5.2b05/
