### ISSUE TITLE
Have a namespacesynopsis? 

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#107]
Still working with documentation (as in #60), I am trying to represent C++ namespaces in DocBook. The only solution I found was to create a new tag, `<namespacesynopsis>` (along with `<namespacesynopsisinfo>`), very much inspired from `<classsynopsis>` (and `<classsynopsisinfo>`). The contents are very similar to that of classes, except that you can defined `<classsynopsis>` within `<namespacesynopsis>`. To be consistent, I also defined `<namespace>` as a clone to `<ooclass>` and `<namespacename>` like `<classname>`. 

Here is my current implementation (potentially with other extensions I am planning to contribute soon): 

```
db.programming.inlines |= db.namespace | db.namespacename

db.namespace.role.attribute = attribute role { text }
db.namespace.attlist =
   db.namespace.role.attribute?
   & db.common.attributes
   & db.common.linking.attributes
db.namespace = element namespace { db.namespace.attlist, db.namespacename }

db.namespacename.role.attribute = attribute role { text }
db.namespacename.attlist =
   db.namespacename.role.attribute?
   & db.common.attributes
   & db.common.linking.attributes
db.namespacename = element namespacename { db.namespacename.attlist, db._text }

## Then the synopsis.
db.synopsis.blocks |= db.namespacesynopsis

db.namespacesynopsisinfo.role.attribute = attribute role { text }
db.namespacesynopsisinfo.attlist =
  db.namespacesynopsisinfo.role.attribute?
  & db.common.attributes
  & db.common.linking.attributes
  & db.verbatim.attributes
db.namespacesynopsisinfo =
  element namespacesynopsisinfo {
    db.namespacesynopsisinfo.attlist, db.verbatim.contentmodel
  }

db.namespacesynopsis.role.attribute = attribute role { text }
db.namespacesynopsis.attlist =
  db.namespacesynopsis.role.attribute?
  & db.common.attributes
  & db.common.linking.attributes
  & db.language.attribute?
db.namespacesynopsis = 
  element namespacesynopsis { 
    db.namespacesynopsis.attlist,
    db.programming.inlines+,
    (db.namespacesynopsisinfo
    | db.classsynopsis
    | db.funcsynopsis
    | db.fieldsynopsis
    | db.typedefsynopsis
    | db.macrosynopsis
    | db.enumsynopsis)*
  }
```

What would you (and the TC) think of this?

**Comment by dourouc05** [comment]
Finally, replying to https://lists.oasis-open.org/archives/docbook-tc/201810/msg00010.html. 

- Name spaces are available in almost all languages. 
- I propose this new tag to contain everything that is within a name space, which is opposed to saying that a class belongs to a name space, for instance. 
- Following the suggestion in https://lists.oasis-open.org/archives/docbook-tc/201810/msg00010.html, how would you use `<info>` to indicate that there is a name space within another name space (like https://doc.qt.io/qt-5.11/qt3dcore.html, with Quick within Qt3DCore)?

**Comment by shudson310** [comment]
Superceded by #111
