### ISSUE TITLE
Have a typedefsynopsis? 

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#109]
In the same vein as #107 and #108, I propose a way to represent C and C++ typedefs, i.e. a shortcut for a long type name that is supposed to be used in user code instead of the long name (inline: `<typedefname>`; synopsis: `<typedefsynopsis>`).

```
    ## First the inline elements. 
    db.programming.inlines |= qdt.typedefname
    
    qdt.typedefname.role.attribute = attribute role { text }
    qdt.typedefname.attlist =
       qdt.typedefname.role.attribute?
       & db.common.attributes
       & db.common.linking.attributes
    qdt.typedefname = element typedefname { qdt.typedefname.attlist, db._text }
    
    ## Then the synopsis.
    db.synopsis.blocks |= qdt.typedefsynopsis
    
    qdt.typedefsynopsis.attlist = 
       db.common.attributes
       & db.common.linking.attributes
       & db.language.attribute?
    qdt.typedefsynopsis = 
      element typedefsynopsis {
        qdt.typedefsynopsis.attlist, 
        qdt.typedefname, 
        db.programming.inlines*
      }
```

**Comment by dourouc05** [comment]
Once more, as per https://lists.oasis-open.org/archives/docbook-tc/201810/msg00010.html. 

- This construct is quite common: C, C++ mostly, but very similar also in SystemVerilog, Haskell, OCaml, Julia, C#, Swift (https://en.wikipedia.org/wiki/Typedef#Other_languages). 
- This semantics is not covered by other tags in DocBook, as far as I could see.

**Comment by shudson310** [comment]
Superceded by #111
