### ISSUE TITLE
Have a macrosynopsis? 

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#110]
Just like #107, #108, and #109, I would need to represent some C and C++ syntax, this this macros. These are really like regular functions, but are implemented as string replacements. Thus, I followed the same model as `<funcsynopsis>`. The major difference is that a macro does not really "return" something, it's rather code rewriting. I think the model I propose is generic enough, as it can for instance represent Julia macros (said to be close to LISP): the macro rewrites the code that is passed as argument, and outputs new code (https://docs.julialang.org/en/v1/manual/metaprogramming/#man-macros-1). 

```
## First the inline elements. 
db.programming.inlines |= db.macro
    
db.macro.role.attribute = attribute role { text }
db.macro.attlist =
  db.macro.role.attribute?
  & db.common.attributes
  & db.common.linking.attributes
db.macro =
  element macro { db.function.attlist, db._text }

## Then the synopsis.
db.synopsis.blocks |= db.macrosynopsis

db.macrosynopsis.role.attribute = attribute role { text }
db.macrosynopsis.attlist =
  db.macrosynopsis.role.attribute?
  & db.common.attributes
  & db.common.linking.attributes
  & db.language.attribute?
db.macrosynopsis.info = db._info.title.forbidden
db.macrosynopsis =
  element macrosynopsis {
    db.macrosynopsis.attlist,
    db.macrosynopsis.info,
    (db.macrosynopsisinfo | db.macroprototype)+
  }

db.macrosynopsisinfo.role.attribute = attribute role { text }
db.macrosynopsisinfo.attlist =
 db.macrosynopsisinfo.role.attribute?
 & db.common.attributes
 & db.common.linking.attributes
 & db.verbatim.attributes
db.macrosynopsisinfo =
 element macrosynopsisinfo {
   db.macrosynopsisinfo.attlist, db.verbatim.contentmodel
 }
 
db.macroprototype.role.attribute = attribute role { text }
db.macroprototype.attlist =
  db.macroprototype.role.attribute?
  & db.common.attributes
  & db.common.linking.attributes
db.macroprototype =
  element macroprototype {
    db.macroprototype.attlist,
    db.modifier*,
    db.macrodef,
    (db.void
     | db.varargs
     | ((db.paramdef | db.group.paramdef)+, db.varargs?)),
    db.modifier*
  }
  
  db.macrodef.role.attribute = attribute role { text }
  db.macrodef.attlist =
    db.macrodef.role.attribute?
    & db.common.attributes
    & db.common.linking.attributes
  db.macrodef =
    element macrodef {
      db.macrodef.attlist, (db._text | db.type | db.macro)*
    }
```

**Comment by dourouc05** [comment]
Following https://lists.oasis-open.org/archives/docbook-tc/201810/msg00010.html. 

- Again, this is not specific to one programming language, albeit the functionality is not as commonly found as enumerations. (For instance, you have some variations of it in C, C++, Julia, Scala, LISP, Rust.)
- The content model is very similar to functions. However, macros tend to work very differently from functions (even though they look similar when users call them); that's why I think a "strict" distinction would be helpful (but a `role` could be enough).

**Comment by shudson310** [comment]
Superceded by #111
