### ISSUE TITLE
refentry in sect1

### ISSUE THREAD

**Issue by petere** [docbook/docbook#112]
DocBook 4 allows `refentry` in `sect1` etc. DocBook 5 does not, but allows it inside `section`. That seems inconsistent.

This seems to be the only difference in the content model between `sect` and `section` (other than that `sect1` permits `sect2` vs. `section`), so perhaps it's an accidental omission.

**Comment by bobstayton** [comment]
I can confirm that this is true, and that it was not intentional.  Thanks for pointing it out.
