### ISSUE TITLE
Allow info in listitem

### ISSUE THREAD

**Issue by ndw** [docbook/docbook#117]
I'm surprised this hasn't come up before, but I don't recall hearing of it.

I have a listitem with which I'd like to associate some metadata, but there's no place for me to put it. I think listitem should allow info.

**Comment by LarryRowland** [comment]
I am curious as to what type of metadata might be directly associated with a list item.  I'm not against it, just curious about what it would look like.

**Comment by ndw** [comment]
I wanted to keep track of the date the item was added, who added it, and some metadata about what geography was involved. There may have been some other items as well, but those are the ones I remember off the top of my head.

**Comment by bobstayton** [comment]
The DocBook Technical Committee approved adding info to listitem at the November 2019 meeting.

**Comment by ndw** [comment]
Hmm. I expected this to be closed automatically by #138 but I guess I got the format wrong.
