### ISSUE TITLE
Graphical XLST Documentation, XLST->SVG Flowcharts? possible?

### ISSUE THREAD

**Issue by dataf3l** [docbook/docbook#121]
Perhaps if there was a way to automatically convert XLST to SVG with flowchart looking diagrams, it should be possible to explain to readers what the XSL files are doing and as a result, this could help people understand the system better, in terms of it's current logic...

**Comment by kosek** [comment]
This issue list is for DocBook schema. But I would suggest not to re-enter for stylesheets -- they are simply too complex to be sensibly visualized.
