### ISSUE TITLE
Propose algorithm float along with figures, tables, and examples?

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#157]
In some cases, I'd like to present algorithms in structures like figures or tables. However, DocBook does not propose any really matching tag... For now, I'm using figures, but it makes no sense (it's just that is works). 

Would it be possible to have an `algorithm` tag, with the same content model as `example` (plus the informal versions)? 

I really don't think that anything else is required: either you can then put your algorithm inside in a `programlisting` (with the right highlighter) or you use a `procedure` if you want something slightly more formal.

**Comment by ndw** [comment]
That seems like something you could easily do with a role value on example.
```
<example role='algorithm'>...</example>
```
 Would that not be sufficient?

**Comment by dourouc05** [comment]
Semantically, it's not an example, that's the problem...

**Comment by ndw** [comment]
The semantics of tags are not wholly bound up in their names. Perhaps figure with an role would be better? How does it fit into the narrative flow semantically? How is it not a "kind of figure"? Figures in particular sometimes get broken into categories: technical drawings, schematics, flow charts, etc.

From one perspective, if you'd expect to have a cross reference of the "as you can see in [thing over there]" sort and if you expect it to have a title and be labeled and maybe float out-of-line, it is a kind of figure. Using role attributes is an easy way to provide additional nuance for your environment without the overhead of inventing whole new elements.

**Comment by dourouc05** [comment]
I'd expect to be able to make references, things like: "This process is detailed in Algorithm X." In larger works, I'd expect to have a Table of Algorithms, just like a Table of Figures, Examples, Tables. In that respect, it is very much like an example or a figure.

**Comment by kosek** [comment]
And what about using procedure element? I think that semantically it is very close to an algorithm.

https://tdg.docbook.org/tdg/5.2/procedure.html

**Comment by dourouc05** [comment]
It's semantically perfect, but it has a very strict model. For instance, I don't think there is a way to include loops in `procedure`. My use case is actually very similar to the LaTeX package algorithm2e (http://ftp.snt.utwente.nl/pub/software/tex/macros/latex/contrib/algorithm2e/doc/algorithm2e.pdf). `figure` is a better container in this case, because a true model here would require an enormous amount of new tags…

**Comment by kosek** [comment]
We can make make steps optional on procedure - that should resolve your issue with using procedure for this usecase?

**Comment by dourouc05** [comment]
I can't think of a better solution! More precisely, you would then allow anything that is already allowed in a `step`, but directly within `procedure`? I'm sold!

**Comment by ndw** [comment]
There's nothing about using a role attribute that prevents you from generating cross references of the form "the process detailed in Algorithm X" or a Table of Algorithms. That was the point I was trying to make earlier.

**Comment by dourouc05** [comment]
That solution would also work. I feel it's less clean, but it does not require any schema change. The question is rather: what would you advise as a long-term solution?

**Comment by ndw** [comment]
Actually, my most recent thought is that we should add a `type` attribute to the formal objects for this purpose. That's consistent with the way the `type` attribute on index terms can be used (variable index, concept index, etc.)

**Comment by dourouc05** [comment]
`type` would be nice and clean, especially as `role` can also be used for profiling. Would it be with a "generic" (in)formal object?

**Comment by ndw** [comment]
I propose adding a `type` attribute to `figure`, `example`, `table`, and `equation` and, for good measure, their "informal" counterparts. If someone argues for adding it to `procedure` as well, I think that would be fine too. I don't think we need another element with a somehow more generic name. I really do think that these things are subclasses of figure and possibly example.

**Comment by dourouc05** [comment]
Thanks for solving this :)!
