### ISSUE TITLE
Get rid of docbook-schemas Maven artifact dependencies

### ISSUE THREAD

**Issue by ddekany** [docbook/docbook#158]
Currently, if your Java project needs the schema files, and you don't want all those dependencies you actually don't need (as it can lead to version conflicts, and more licenses to review, some extra size), you have to do this:

        <dependency>
            <groupId>org.docbook</groupId>
            <artifactId>docbook-schemas</artifactId>
            <version>5.1-1</version>
            
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-slf4j-impl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>jcl-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.sf.saxon</groupId>
                    <artifactId>Saxon-HE</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.xmlresolver</groupId>
                    <artifactId>xmlresolver</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

I saw all these dependencies are pulled in because of `org.docbook.Schemas`, which is used to generate a catalog file. But, certainly you don't need external libraries to read XML files and transform them into a single XML file. Even if it's done with XSLT, core Java can do that for a long time now. I'm also not sure if generating the unified catalog file has to be on the fly, instead of being done on build time.

Also, in my case, I don't need `org.docbook.Schemas` at all. If that's not just me, then there could be a `docbook-schemas-resources` artifact that only contains the resources, and `docbook-schemas` should depend on that.

Also, `org.apache.logging.log4j` and `jcl-over-slf4j` dependencies shouldn't be present. After all, the whole point of SLF4J is that your artifact won't assume a concrete logging library.

Also, resource paths should start with `org/docbook/`, though changing that now is not backward compatible.

**Comment by ndw** [comment]
Yes. It's a bit of a mess. Can you point me to an example of a "-resources" artifact?

**Comment by ddekany** [comment]
By "-resources" artifact I just meant a plain jar artifact that doesn't have `org.docbook.Schemas` in it. But of course the best would be if `org.docbook.Schemas` is not needed (not sure if generating that catalog file has to be dynamic, like if it contains some absolute paths that are only known on runtime). Or if it's needed, then it only depends on standard Java classes. Creating a `-resources` artifact is the last resort.

**Comment by ndw** [comment]
I completely agree. I think two-years-ago-me misunderstood some things :-)

I'm just wondering what a Maven jar that only contains resources looks like. I haven't actually tried building one, but Maven usually wants a source jar and an artifact jar and a POM file, etc., and I'm just not sure what those should contain for a Maven artifact that just contains a handful of schema files.

**Comment by ddekany** [comment]
It's not a special case. I think the thing you miss is that Java packages can not only contain classes, but files with file extensions other than "class" as well. Those files we usually call "resources". So it really just an ordinary Maven project that happens to have 0 classes in it.

That's also why having resources under `etc` and `schema` is  weird. With that, in theory, you are claiming the `etc` and `schema` top-level packages to yourself. But you really only meant to claim `org.docbook` (which is maybe also too much... `org.docbook.schema` maybe?). With the introduction of modules in Java 9, this becomes more than aesthetics. But, to fix these, you should use a new Maven group and/or name...

**Comment by ndw** [comment]
If you grab this snapshot, you'll see what I've accomplished so far: `org.docbook:docbook-schemas:5.2b10-SNAPSHOT`. That's currently in the Sonatype snapshots repository, `https://oss.sonatype.org/content/repositories/snapshots`

I can't work out how to browse that repository, so I just stuck it in a project and downloaded it.

It's got all of the schemas that the previous release included, and a single Java class so that I could make the Sonatype maven publication system happy (if it's possible to publish without a sources jar and a javadoc jar, I haven't worked out how).

The single Java class is just a single static final variable that lists the DocBook versions included. It has no dependencies.

I've moved the schemas down to `org/docbook/schemas/...` and setup catalogs for them. Testing those is next on my list.

**Comment by ddekany** [comment]
That published artifact itself works for me. Except, you have changed the resource paths, which breaks backwards compatibility, so, in theory, you are supposed to change the project name. Although it's not very likely that two independently developed components of a project depend on different incompatible versions of `org.docbook:docbook-schemas`, so maybe you can get away with this without causing to much pain.

I guess javadoc and sources are mandatory, but Java classes shouldn't be. Not sure what exactly chokes on that and how. Also your source artifact contains something else, not the actual sources. Though practically that's only useful if you have compiled classes that the IDE can navigate to... like a single package-info.java? :)

**Comment by ndw** [comment]
I'm happy to change the name to `org.docbook:schemas` to avoid the backwards incompatibility problem. Not sure why I put the redundancy in there in the first place, really.

I couldn't make a single package-info.java work without at least one class. The static list of version numbers strikes me as harmless and/or marginally useful.

**Comment by ddekany** [comment]
If you really have to add a class, then static final constants that contain the path of the key resources (like of the rng files) would be much more useful.

**Comment by ndw** [comment]
The path within the jar file would be easy. I'd rather not try to work out the actual `jar:file:` absolute path because that may or may not even be possible depending on the classloader.

**Comment by ddekany** [comment]
Yes, I meant things like public `static final String DOCBOOK_5_0_RNG_RESOURCE_PATH = "/org/docbook/schemas/5.0/rng/docbook.rng"`. But now that you are saying, you can easily turns that into an URL: `DocBook.class.getResource(DOCBOOK_5_0_RNG_RESOURCE_PATH)`. This is what user will do with the resource path anyway. It also can be unit tested to not return `null` (which means that there's a mistake in the path).

Also, I have just noticed that the DocBook class is missing from the jar artifact. Also its source is not under `docbook/src/main/java`, or anywhere for that matter. Probably you should make the build more conventional, to avoid such accidents.

**Comment by ndw** [comment]
Yes, fair enough. I thought I was being clever generating part of that class in the build, but maybe that's not really clever :-)

I think I fixed the missing class problem yesterday, but I'll do a little more on it this afternoon.

**Comment by ddekany** [comment]
Generated sources is also a pretty standard thing, you will find examples of it.

**Comment by ndw** [comment]
IIRC, multiple jar files containing the same package can be problematic. Suppose we wanted to release the Publisher's schema (or other schemas) on Maven (and why wouldn't we?). We'd have a few choices:

1. Put them all in a single jar. This has some appeal, though it would make the jar file that much larger and would significantly complicate versioning.
2. Put them in different jars, in which case different packages would be better (I think).

Perhaps instead of `org.docbook.schemas`, we should have `org.docbook.docbook`, `org.docbook.publishers`, etc. It looks a little odd, but it's not wholly unreasonable.

**Comment by ddekany** [comment]
Yes, with the new class loaders introduced Java 9 (i.e., with Java modules) it's not allowed to have multiple jar-s that contribute to the same package. (With the more commonly used traditional class loader it's allowed.)

Maybe org.docbook.schemes.docbook and org.docbook.schemes.publisher.
