### ISSUE TITLE
Allow pubwork attribute on biblioentry

### ISSUE THREAD

**Issue by rlhamilton** [docbook/docbook#164]
There is no way to indicate directly what type of resource (book, article, paper, etc.) a biblioentry refers to. There are indirect means, such as using citetitle instead of title and using pubwork on that element, but there is no good way to directly indicate the type of entry.

I propose that the existing pubwork attribute be allowed on biblioentry.

It may also be time to review the enumerated values on pubwork. Some are getting a bit old (e.g., bbs, gopher, cdrom).

**Comment by shudson310** [comment]
ACCEPTED: add @pubwork to biblioentry. Change @pubwork to add "other" enumeration for extension.
