### ISSUE TITLE
DB5.1: Schematron anomaly with the rule: "Root must have version"

### ISSUE THREAD

**Issue by rlhamilton** [docbook/docbook#172]
The embedded schematron pattern titled "Root must have version" is incorrectly formed in the version currently online at OASIS (all four versions with and without xi and both rnc and rng):
https://docs.oasis-open.org/docbook/docbook/v5.1/os/schemas/rng/

The title element that contains that text does not have the namespace prefix s. This is only the case with patterns with this title; all the other patterns have titles with the prefix.

This doesn't appear to have an impact on RelaxNG validation (I've been using those schemas for a long time). However, the docbook.sch and docbookxi.sch files are missing the "Root must have version" rules. I'm guessing that they are generated from the embedded rules and the processor skips them.

The good news is that this problem is fixed in 5.2 and is not present in 5.0.1, but if anyone is using 5.1 and gets the schema from the OASIS page, they'll get a schema with this problem.

**Comment by ndw** [comment]
I believe this was one of the motivations for 5.0.1.

**Comment by rlhamilton** [comment]
Could be, but it looks like the fix didn't get carried forward to 5.1.

**Comment by bobstayton** [comment]
First priority is to get this fixed in the source for 5.2.    Can Jirka or Norm please confirm that this is fixed in the source?
Then we will start work on a 5.1.1 release to correct this error for 5.1 users.

**Comment by ndw** [comment]
It appears to me that 5.2 and 5.0.1 are both correct. The problem appears only in 5.1 as far as I can see.

* https://docbook.org/xml/5.2b09/rng/docbook.rng ✔️ 
* https://docbook.org/xml/5.1/rng/docbook.rng ❌ 
* https://docbook.org/xml/5.0.1/rng/docbook.rng ✔️

**Comment by rlhamilton** [comment]
Hi Norm,

That’s what I remember (though it’s been a while:).

Dick
-------
XML Press
XML for Technical Communicators
http://xmlpress.net
hamilton@xmlpress.net

**Comment by ndw** [comment]
The PR in #181 fixes this issue.

**Comment by shudson310** [comment]
The PR in #181 fixes this issue. Bob preparing v5.1.1 through OASIS process.
