### ISSUE TITLE
Adding dbits + XInclude -> dbitsxi.rn[cg] Schema?

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#179]
# Situation

The DocBook schema files contain a version with and without XIncludes.

According to the latest schema release on [docbook.org](https://docbook.org/xml/5.2b09/rng/), we have also the DocBook [ITS schema](https://en.wikipedia.org/wiki/Internationalization_Tag_Set), the International Translation Set. If I'm not mistaken, we have only a version *without* XIncludes (`dbits.rn[cg]`) for this schema.

# Suggestion Solution

Could we also release a `dbitsxi.rn[cg]` version with XIncludes?

We probably need to provide this for version 5.1 and later.

**Comment by ndw** [comment]
Sure. Looking at the combinatorics, I sort of wonder if the XInclude variants were a good idea. I think things have developed to the point where XInclude is allowed almost everywhere, so there's no real pre-XInclude validation. Given that you have to do validation post-XInclude to get useful results anyway, maybe we would have been better to ignore XInclude in the schemas.

But it's too late for that now, I guess.

**Comment by kosek** [comment]
I think that XInclude variants are still useful for example for nxml mode in Emacs where schema is used for guiding element completion.

**Comment by ndw** [comment]
Fair point.
