### ISSUE TITLE
title and titleabbrev: do they both need to be either inside <info> or outside?

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#180]
I'm currently working on automatically generating DocBook documents (from inside [LyX](https://www.lyx.org/)). I encountered a document with a running title for a section, which calls for `<titleabbrev>`. However, the following form is not accepted by the schema:

```xml
<book xml:lang="en_US" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.2">
<title>Untitled Document</title>
<chapter xml:id="chap.intro">
<title>Chapter Heading</title>
<info>
<titleabbrev>chapter heading in the running head</titleabbrev>
<!-- other things in info… -->
</info>
<!-- chapter content -->
</chapter>
</book>
```

According to the grammar, either `<title>` and `<abbrevtitle>` are inside `<info>` or outside it: 

```xml
<book xml:lang="en_US" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.2">
<title>Untitled Document</title>
<chapter xml:id="chap.intro">
<info>
<title>Chapter Heading</title>
<titleabbrev>chapter heading in the running head</titleabbrev>
<!-- other things in info… -->
</info>
<!-- chapter content -->
</chapter>
</book>
```

```xml
<book xml:lang="en_US" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.2">
<title>Untitled Document</title>
<chapter xml:id="chap.intro">
<title>Chapter Heading</title>
<titleabbrev>chapter heading in the running head</titleabbrev>
<info>
<!-- other things in info… -->
</info>
<!-- chapter content -->
</chapter>
</book>
```

For me, it would be much more convenient if I could have `<title>` outside `<info>` (it's needed for all chapters, sections, etc.) and `<titleabbrev>` inside `<info>` (it's not required to have a readable document, it's only needed to make the output nicer, unlike, say, a subtitle), like in the first example. 

When reading the documentation, I really thought that all these constructs were allowed ()https://tdg.docbook.org/tdg/5.2/titleabbrev.html.

**Comment by kosek** [comment]
> When reading the documentation, I really thought that all these constructs were allowed ()https://tdg.docbook.org/tdg/5.2/titleabbrev.html.

What on this page makes you think that what you want is allowed?

**Comment by ndw** [comment]
If you're generating the content, I don't understand how it can be substantially more difficult to put `title` and `titleabbrev` *either* both inside `info` or both outside.

**Comment by dourouc05** [comment]
> > When reading the documentation, I really thought that all these constructs were allowed ()https://tdg.docbook.org/tdg/5.2/titleabbrev.html.
> 
> What on this page makes you think that what you want is allowed?

It's rather the opposite: nothing indicates that this is not allowed, or that there is any required order between the titles, or anything.

**Comment by ndw** [comment]
That page is about what can go *in* a `titleabbrev`, not where it's allowed. Unless I'm misunderstanding what you're pointing to.

**Comment by shudson310** [comment]
The TC is not inclined to change the schema.

**Comment by dourouc05** [comment]
Sorry for the delay, I'm only seeing that there has been answers. Given that the schema will not change (which is fine), could a documentation change be provided? Each reference page of the TDG provides information, for each element, on **both** where it is allowed (the Parents section) **and** what is allowed inside (most of the page). A paragraph such as the following could be included in the page about `subtitle` and `titleabbrev`, under Description, for instance: 

> If present, the `titleabbrev` tag must be present at the same level as the `title` tag. More precisely, if the `title` tag is in an `info` container, `titleabbrev` should be inside the same container; conversely, if `title` is not in the `info` container, `titleabbrev` should not be inside either.

The corresponding constraint is not exactly super intuitive (`info` elements mostly indicate that you can put some things inside and others outside, with the vast majority of the elements having to be within the container), I think that it's useful to repeat this quite often (this is usually a good paedagogical practice).

**Comment by bobstayton** [comment]
Yes, I have requested that the documentation be changed to clarify this.

**Comment by ndw** [comment]
The following paragraph has been added to the documentation for `title`, `titleabbrev`, and `subtitle`:

> Titles are so common, and so often the only “info” elements associated with their parent, that they (title, subtitle, and titleabbrev) are allowed outside the info element. This is a tradeoff favoring author convenience over a small amount of additional complexity in processing. However, the title elements must either all be outside of the info wrapper or all inside, you cannot have some outside and some inside.

If that isn't clear, please let me know.

**Comment by dourouc05** [comment]
That's clear enough for me, thanks!
