### ISSUE TITLE
In dbits, what is the purpose of its-any-element?

### ISSUE THREAD

**Issue by ndw** [docbook/docbook#182]
In `its20.rnc`, there's a pattern named `its-any-element` but it doesn't appear to be used. Is it intended to be used by customizers?

It is currently defined as `element * { ... }` which means it's actually *any* element, not any ITS element, should it be defined as `element its:* { ... }`?

**Comment by kosek** [comment]
The schema is taken from the ITS 2.0 spec, https://github.com/w3c/its-2.0-testsuite/blob/master/its2.0/schema/its20.rng

In DocBook context this pattern is of no use and can be deleted from `its20.rnc`. I think that I might have added pattern during ITS schema development and then haven't noticed that it's actually not used. Or might be idea was to provide some building block for people who can't use NVDL and who don't have RELAX NG schema for their vocabulary and can't just plug `its20.rnc` into their schema. 

BTW `its-` is common prefix in ITS 2.0 schema so it can be combined with other schemas (similar do `db.` prefix used in DocBook schemas). So I believe that `its-any-element` has been meant to allow any element not only elements in ITS namespace.

**Comment by ndw** [comment]
Okidoke.
