### ISSUE TITLE
use correct OASIS URLs in catalog.xml

### ISSUE THREAD

**Issue by bobstayton** [docbook/docbook#201]
The catalog.xml file should map the official published schema urls to local files.  However, the catalog in 5.1 does not contain the published schema urls.  For example, the OASIS site where the RNG files for 5.1 are available is:

http://docs.oasis-open.org/docbook/docbook/v5.1/os/schemas/rng/
 
where "os" means OASIS Standard.   But the catalog.xml file uses:

http://www.oasis-open.org/docbook/xml/5.1CR4/rng/

For 5.2, the final urls should be:

http://docs.oasis-open.org/docbook/docbook/v5.2/os/schemas/rng/

During the OASIS process for approval, these need to track the actual location of the draft files, such as:

http://docs.oasis-open.org/docbook/docbook/v5.2/csd01/schemas/rng/

where "csd01" means Committee Specification Draft 01".  These must be updated with each iteration of the process until it is approved as an OASIS Standard.

**Comment by ndw** [comment]
Okay. I can fix the 5.2 builds. I think the `/docbook/` URIs used to work, back in the last millennium, perhaps before `docs.oasis-open.org` was standardized.

I'll fix the builds for 5.2. I suggest you fix the catalog "by hand" for 5.1.1 but if you want me to patch the build for that too, let me know.

**Comment by bobstayton** [comment]
I will fix the 5.1.1 catalog by hand.

**Comment by ndw** [comment]
I think I've fixed this.
