### ISSUE TITLE
Assembly: allow <structure> as root element?

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#219]
# Problem

When I try to write an assembly document, I usually start with `<assembly>`. However, there are situations when you need to deviate from that procedure. For example, when you have a really big list of modules, or big structure, you would like to split the contents into different files and xinclude them. It makes such an assembly file much more readable and much easier to handle.

The current assembly files `assembly{,xi}.rn{c,g}` of version 5.2 allow the following root elements:

* `<assembly>`
* `<module>`
* `<relationships>`
* `<resources>`
* `<transforms>`

However, you can't write a separate file with a `<structure>`. This is missing from the list. Upon further inspection, the assembly schemas clearly shows it's not there (RNC):

```
start =
  db.assembly
  | db.resources
  | db.relationships
  | db.transforms
  | db.module
```

Surprisingly, `<module>` is there, but not its parent element `<structure>`.

# Possible solution

Maybe there are some deeper thoughts which I'm not aware of it. Allowing the above elements but not `<structure>` is confusing. I would have expected to be able to select this element as root element.

Could we add that missing element into the list of possible root elements?

**Comment by bobstayton** [comment]
I agree that structure should be allowed as a top level element in a document.

**Comment by bobstayton** [comment]
The DocBook Technical Committee approved this change on 11 August 2021.

**Comment by ndw** [comment]
Should it also have an `info` element so that metadata about it can be recorded in the file?

**Comment by shudson310** [comment]
Sounds right to me. I am in favor of it.

--Scott

**Comment by ndw** [comment]
Nevermind. The `info` element *is* already there, it's just a strange content model that doesn't require it to be first:
```
      element structure {
         db.structure.attlist,
         (db.output* & db.filterin? & db.filterout? & db.structure.info),
         db.merge?,
         db.revhistory?,
         db.module+
      }
```
I think it might have been better as `db.structure.info?, (db.output* & db.filterin? & db.filterout?)` but I don't think it's worth the backwards-incompatiblity hit to do it. And maybe there was a reason I no longer recall!
