### ISSUE TITLE
Allow anchor in tr?

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#233]
`anchor` is allowed mostly anywhere, but not in `tr`. I think it would make sense to allow it there (and in CALS' row too), because `anchor` is allowed in general wherever there is some content (that is, everywhere except `info`). The semantics would be to point at that specific row (and not a given cell, which is the case of an `anchor` within a `td`).

This is my use case (excerpt of https://doc.qt.io/qt-6/qml-glossary.html): 

```xml
<db:informaltable style="generic">
<db:thead>
<db:tr>
<db:th>
<db:para>Term</db:para>
</db:th>
<db:th>
<db:para>Definition</db:para>
</db:th>
</db:tr>
</db:thead>
<db:tr valign="top">
<db:td>
<db:para>Signal Handler</db:para>
</db:td>
<db:td>
<db:para>A signal handler is the expression (or function) which is triggered by a signal. It is also known as a &quot;slot&quot; in C++.</db:para>
<db:para>See <db:link xlink:href="">Signal and Handler Event System</db:link> for more details.</db:para>
</db:td>
</db:tr>
<db:tr valign="top">
<db:anchor xml:id="lazy-instantiation"/>
<db:td>
<db:para>Lazy Instantiation</db:para>
</db:td>
<db:td>
<db:para>Object instances can be instantiated &quot;lazily&quot; at run-time, to avoid performing unnecessary work until needed. Qt Quick provides the <db:link xlink:href="">Loader</db:link> type to make lazy instantiation more convenient.</db:para>
</db:td>
</db:tr>
</db:informaltable>
```

**Comment by ndw** [comment]
No, that's never going to be practical. Neither the CALS table model nor the HTML table model allow you to mix other stuff in there. If you want to link to a row, put an ID on it. If you want to link to a cell, put an ID on it. If you don't want to use IDs on the table elements, put the anchor inside the cell where you'd like the target to be.

Rendering the table in either HTML or FO or XML+CSS would, in every case, require the stylesheets to work out what row or cell the anchor could conceivable be referring to and do this for you anyway. There's no system that I'm aware of that makes linking "between" cells a meaningful concept.

**Comment by dourouc05** [comment]
Thanks for the detailed explanation! I'm closing the issue.
