### ISSUE TITLE
Allow `<topic>`s to be nested like `<section>`

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#240]
# Situation

On the [docbook mailinglist](https://lists.oasis-open.org/archives/docbook/202211/msg00012.html) I've started a discussion about topic-oriented writing.

Currently, the  [`<topic>`](https://tdg.docbook.org/tdg/5.2/topic.html#element.db.topic) element allows different block and division elements, however, `topic` is not in this list. This is a bit awkward as the element advertise itself as (emphasize by me):

> A **modular unit** of documentation not part of any particular narrative flow.
> [...]
> The topic element is a **general-purpose container** designed to be semantically neutral with respect to any narrative flow.

Shouldn't a _modular unit_ and a _general-purpose container_ be allowed to be nested? Users coming from DITA would probably be confused as this is not the case.

We could use `<section>` as parent and child elements, but it brings some semantic baggage.

# Proposal

I would like to suggest to lift the restriction on `<topic>`. We could see this idea with two sides:

1. Make `<topic>` similar to `<section>` in the sense as it is allowed to be nested. This would make this element more useful in topic-oriented writing.
2. Allow `<topic>` to be used as a replacement for `<book>`, `<set>`, or `<article>`. This would make this element truely a very generic, all-purpose container.

Item (2) would be probably the more drastic approach. Perhaps something for DocBook 6.0?

If you think this suggestion is useful, don't only change the content model, but implement this in the stylesheets too (if possible, also for the XSLT 1.0).

Thanks!

# Benefits

* Make DocBook a format which is ready for topic-oriented writing.
* Make migration from DITA easier.
* Make mix and match with DITA easier.
* Reduce confusion with other formats (like DITA) which can use a `<topic>` element in a very generic way.

**Comment by ndw** [comment]
Okay, I confess, I've never drunk the DITA kool aid. I'm sure there are benefits to authoring in a modular style, and I'm sure that there are cases where that can be leveraged to the publishers advantage.

But what is the point of allowing topics to nest? If a topic is meant to be a single nugget of information, what does it mean for that nugget to be decomposed further? If a topic stands on its own, how can it rely on other topics? If a topic is nested inside another topic as a kind of subtopic, how does *it* stand on its own?

I would have thought that
1. Topics too large to stand alone without subtopics would be decomposed by the author into separate, stand-alone topics.
2. If you decided that you needed substructure within a single topic, you'd use sections.
3. If you want to group topics together, there are already wrappers for that.

I don't actually care. I'm not going to lie down in the road and refuse to accept nested topics if that's what users need. But if you have nested topics that don't stand alone, what you have is a larger narrative unit divided into sections. Calling those sections topics to make migration to and from DITA easier doesn't seem like a very principled approach.

I observe also that you can use assemblies to pull together distinct topics into a nested hierarchy if you want. Not everything you publish has to be authored in precisely the arrangement of the published artifact. It follows, IMHO, that not every kind of published artifact has to be "valid DocBook" precisely as it's arranged for publication.

But, you know, I've been wrong before.

**Comment by bobstayton** [comment]
The topic element is not nested by design.  The topic element was introduced in DocBook 5.1 as one component of a new modular documentation design for DocBook.  It is meant to be used  with the assembly element in 5.1, which enables you to nest topics as needed at assembly time by nesting module elements in the assembly, rather than at authoring time.  The assembly design lets you morph a topic into a section at assembly time, or into a chapter or an appendix or whatever.  If you need to author a nested "topic", write it as a modular section with subsections, and pull that into your assembly as whatever.

**Comment by tomschr** [comment]
Thanks for the detailed answers. Much appreciated!

I can see your point. It seems a bit more of a philosophical question rather than a technical one. For the time being, I close it.

Thanks anyway for considering it. Much appreciated!
