### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by paledega** [docbook/docbook#255]
```
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /tmp/ymp-build/49db3c235263229b75f963bf92add683/xdg-utils-1.1.3/scripts/html/../desc/xdg-open.xml does not validate
make[1]: *** [Makefile:111: html/xdg-icon-resource.html] Error 13
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:111: html/xdg-desktop-menu.html] Error 13
make[1]: *** [Makefile:111: html/xdg-mime.html] Error 13
```

**Comment by ndw** [comment]
Use an [XML Catalog](https://xmlcatalogs.org/) to map the http: URIs to a local copy on your filesystem. Exactly how to tell your processor to use a catalog depends on the processor. DocBook 4.1.2 ships with a catalog (`docbook.cat`) that will "just work" if you are using a public identifier to locate the schema.

It's possible that the I/O error you experienced was transient. That URI seems to resolve to the DocBook schema for me, today, from Wales.

(I'm going to close this issue, but if the explanation isn't sufficient to fix your problem, please re-open it or send mail to the docbook-apps mailing list.)
