### ISSUE TITLE
Makefile and pipelines are not very Windows friendly

### ISSUE THREAD

**Issue by kosek** [docbook/docbook#4]
Running pipeline on Windows box is not that easy. Some things can be solved easily, for example

 <p:log href="/tmp/i.xml" port="result"/>

can be replaced by using some relative subdirectory. Some things like

<p:exec command="trang"> would be harder to solve.

**Comment by ndw** [comment]
The presence of p:log statements is a bug. It's all gradle now, so it should be portable. Please open a specific issue if you still have troubles.
