### ISSUE TITLE
Allow multimediaparam in imagedata

### ISSUE THREAD

**Issue by ndw** [docbook/docbook#52]
See issue #49 

The problem is that in order to generate a srcset (or a picture, I expect) you need to know more about the images and their relationships than is currently provided in the markup. The syntax(es) for doing responsive images seem to be...unsettled...in the HTML community.

**Comment by kosek** [comment]
I will re-evaluate HTML 5.1 and picture element and based on this I will propose either mapping from DocBook mediaobject element or propose new markup.

**Comment by kosek** [comment]
See #49 for follow up.

**Comment by kosek** [comment]
Accepted by DocBook TC, implemented in 5.2b02 (see https://github.com/docbook/docbook/pull/92)
