### ISSUE TITLE
Add <danger> to the list of admonitions 

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#55]
Copied from SF: https://sourceforge.net/p/docbook/rfes/311/
Discussion originated from https://lists.oasis-open.org/archives/docbook/201604/msg00003.html

## Proposal
Currently, we have `tip`, `note`, `important`, `warning`, and `caution` as admonition elements. The list is sorted from lowest to highest "severity".

Although you can always markup your "dangerous note" with `<caution>` and `@role`, this solution is considered inappropriate for the following reasons:

* There is a need to have `<danger>`
* Matches well with the ANSI Z535 standard
* It's consistent with the other admonition elements (role feels awkward)
* Aligns well with DITA if someone has to exchange documents
* From a language perspective, <danger> expresses a higher risk of injury and/or death than <caution> (or any other admonition elements).

It would be great if the committee can discuss this proposal.

## Solution

Add the element danger to the other admonitions. Here is a short RNC code snippet:

```rnc
div {
  db.danger.role.attribute = attribute role { text }
  db.danger.attlist =
      db.danger.role.attribute?
        & db.common.attributes
        & db.common.linking.attributes
  db.danger =
    ## A note of danger
    element danger { db.danger.attlist, db.admonition.contentmodel }
}
```

**Comment by kosek** [comment]
Implemented in https://github.com/docbook/docbook/pull/64
