### ISSUE TITLE
Add buildtarget element

### ISSUE THREAD

**Issue by gaborbsd** [docbook/docbook#6]
For make, Ant etc. build targets. Should be allowed inline and should allow replaceable inside. The latter is useful to describe a group of targets with a replaceable suffix that have a similar outcome.

**Comment by shudson310** [comment]
Please provide an example of the intended usage. The TC would like to understand how this would work in different build environment contexts (ant, make, maven, travis, etc.). Should there be a more generic <target> element, or other elements that might be needed to describe this?

**Comment by gaborbsd** [comment]
<step>
	<para>The <buildtarget>extract</buildtarget> target is run.
	  It looks for the port's distribution file (typically a
	  <command>gzip</command>ped tarball) in
	  <varname>DISTDIR</varname> and unpacks it into a temporary
	  subdirectory specified by <varname>WRKDIR</varname>
	  (defaults to <filename>work</filename>).</para>
      </step>

      <step>
	<para>The <buildtarget>patch</buildtarget> target is run.
	  First, any patches defined in <varname>PATCHFILES</varname>
	  are applied.  Second, if any patch files named
	  <filename>patch-<replaceable>*</replaceable></filename> are
	  found in <varname>PATCHDIR</varname> (defaults to the
	  <filename>files</filename> subdirectory), they are applied
	  at this time in alphabetical order.</para>
      </step>

This is taken from FreeBSD Porters' Handbook (we use a customzied DB5 schema), you can see the whole XML [here](https://svnweb.freebsd.org/doc/head/en_US.ISO8859-1/books/porters-handbook/slow-porting/chapter.xml?view=co&revision=49287&content-type=text%2Fplain). And the [rendered version.](https://www.freebsd.org/doc/en/books/porters-handbook/slow-porting.html)

**Comment by kosek** [comment]
This change is implemented in the new beta schema release available at:

https://docbook.org/xml/5.2b04/

Please test it and give us feedback.

**Comment by gaborbsd** [comment]
Thank you for adding this element to the schema!

I believe that it should also be allowed inside userinput. It is quite common that we quote command lines when the build target is referred, e.g.:

```xml
<para>To build the software, run the <buildtarget>all</buildtarget> target:</para>
	
<screen><userinput><command>make</command> <buildtarget>all</buildtarget></userinput></screen>

**Comment by kosek** [comment]
So adding buildtarget to db.os.inlines pattern as well to existing db.programming.inlines should do the trick. Lets TC discuss this at their next meeting and eventually we can extended places where buildtarget is allowed in the next release.

**Comment by gaborbsd** [comment]
Yes, I think so. At FreeBSD, we extensively refer to buildtarget in userinput so with the current implementation, we will still need schema customization for this. Do you mean the next beta or 5.3? It's such a small addition, it would be nice if it could fit into the final 5.2. :)

**Comment by kosek** [comment]
Of course I meant next beta release, V5.2b05, that should be released after next DocBook TC meeting with agreed changes.
