### ISSUE TITLE
Allow <void> within <funcdef>? 

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#60]
# Problem

Naturally, when writing a void function definition, I would do the following, based on what is possible with methods (i.e. using a `<void>` element): 

```xml
<db:funcsynopsis>
   <db:funcprototype>
      <db:funcdef>
         <db:void/>
         <db:function>qmlClearTypeRegistrations</db:function>
      </db:funcdef>
      <db:void/>
   </db:funcprototype>
</db:funcsynopsis>
```

Instead, I'm forced to use `<db:type>void</db:type>` in my documents, which I feel is inconsistent (and makes me write a little bit more code to deal with it, as a nice side effect). 

```xml
<db:funcsynopsis>
   <db:funcprototype>
      <db:funcdef>
         <db:type>void</db:type> <!-- Instead of the more specific element <db:void/> -->
         <db:function>qmlClearTypeRegistrations</db:function>
      </db:funcdef>
      <db:void/>
   </db:funcprototype>
</db:funcsynopsis>
```

# Solution

I would allow `<void>` wherever `<type>` is allowed, i.e.: 

```
db.funcdef =
  element funcdef {
    db.funcdef.attlist, (db._text | db.type | db.void | db.function)*
  }
```

**Comment by kosek** [comment]
DocBook TC agreed to add this into 5.2 (see https://lists.oasis-open.org/archives/docbook-tc/201606/msg00024.html)

**Comment by kosek** [comment]
Implemented in https://github.com/docbook/docbook/pull/57
