### ISSUE TITLE
(Re)allow recursive use of <optional>

### ISSUE THREAD

**Issue by JuergenPurtz** [docbook/docbook#74]
Formal languages and parameter of tools or commands usually contain optional elements. In many cases those optional elements have a recursive structure or contain other optional elements, eg: 

https://www.postgresql.org/docs/current/static/sql-select.html (optional 'RECURSIVE' key word within optional 'WITH'-clause)

http://www.json.org/ (A 'number' optionally contains an 'e' or 'E', which indicates the use of the scientific notation. In this case a '+' or '-' may follow optionally.)

https://docs.oracle.com/javase/specs/jls/se7/html/jls-18.html  (Optional 'Annotations' within optional 'package'-declaration of 'CompilationUnit')

DocBook offers the element < optional > for those constructions. In version 4.x it was possible to use <optional> in a recusive manner. Unfortunatelly since version 5.x this is no longer allowed. **In my opinion it is necessary that the recursivity is re-allowed in further versions of DocBook.**

It is worth mentioning that not only < optional > is affected during the upgrade. It seems that the content model of "technical inline elements" (%tech.char.class; ?) changed significant from version 4.x to 5.x. I go along with some of those changes, but not to the changes to < optional > and < option >, see the old discussion concerning this issue:
https://lists.oasis-open.org/archives/docbook/201606/msg00012.html
https://lists.oasis-open.org/archives/docbook/201606/msg00013.html

**Comment by ndw** [comment]
Glancing at the content model for optional, I'm a little surprised that making it recursive is sufficient, but I'll do it for the next beta.

**Comment by ndw** [comment]
This has been implemented in DocBook 5.2
