### ISSUE TITLE
An error with croatian-specific letters when put in a level 1 heading

### ISSUE THREAD

**Issue by greguric** [docbook/docbook#77]
Hi,
I ran into a problem when trying to convert a txt file to a pdf. I am sending you an xml file as an example of what's going on when I try to do that.
The first one is a plain .txt file used as a source
[test.txt](https://github.com/docbook/docbook/files/723427/test.txt)

This one is an xml file produced by a2x -vkf pdf test.txt
[test_error.txt](https://github.com/docbook/docbook/files/723428/test_error.txt)

And this is a2x output:

marko@dell:~/Brackets$ a2x -vkf pdf test.txt 
a2x: args: ['-vkf', 'pdf', 'test.txt']
a2x: resource files: []
a2x: resource directories: ['/etc/asciidoc/images', '/etc/asciidoc/stylesheets']
a2x: executing: "/usr/bin/asciidoc" --backend docbook -a "a2x-format=pdf"  --verbose  --out-file "/home/marko/Brackets/test.xml" "/home/marko/Brackets/test.txt"

asciidoc: reading: /etc/asciidoc/asciidoc.conf
asciidoc: reading: /etc/asciidoc/asciidoc.conf
asciidoc: reading: /home/marko/Brackets/test.txt
asciidoc: reading: /etc/asciidoc/docbook45.conf
asciidoc: reading: /etc/asciidoc/filters/source/source-highlight-filter.conf
asciidoc: reading: /etc/asciidoc/filters/music/music-filter.conf
asciidoc: reading: /etc/asciidoc/filters/code/code-filter.conf
asciidoc: reading: /etc/asciidoc/filters/graphviz/graphviz-filter.conf
asciidoc: reading: /etc/asciidoc/filters/latex/latex-filter.conf
asciidoc: reading: /etc/asciidoc/lang-en.conf
asciidoc: writing: /home/marko/Brackets/test.xml

a2x: executing: "xmllint" --nonet --noout --valid "/home/marko/Brackets/test.xml"

a2x: executing: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty"  -V  "/home/marko/Brackets/test.xml"

Build the book set list...
xsltproc -o /tmp/tmp3v1tWV/doclist.txt --xinclude --xincludestyle doclist.xsl /home/marko/Brackets/test.xml
Build the listings...
xsltproc -o /tmp/tmp3v1tWV/listings.xml --xinclude --xincludestyle --param current.dir '/home/marko/Brackets' /usr/share/dblatex/xsl/common/mklistings.xsl /home/marko/Brackets/test.xml
xsltproc -o test.rtex --xinclude --xincludestyle --param current.dir '/home/marko/Brackets' --param listings.xml '/tmp/tmp3v1tWV/listings.xml' /tmp/tmp3v1tWV/custom.xsl /home/marko/Brackets/test.xml
XSLT stylesheets DocBook - LaTeX 2e (0.3.4-2)

Image 'dblatex' not found
Build test.pdf
built-in module pdftex registered
no support found for ifthen
no support found for ifxetex
no support found for fontspec
no support found for xltxtra
no support found for fontenc
no support found for inputenc
no support found for fancybox
built-in module makeidx registered
no support found for asciidoc-dblatex
building additional files...
checking if compiling is necessary...
the output file doesn't exist
pdflatex -interaction=batchmode test.tex
pdflatex failed
test.aux:23: Missing \endcsname inserted.
test.aux:23: leading text: ...rash doocbook \v {z}\relax }{section.1}{}}
Unexpected error occured
Error: pdflatex compilation failed

a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty"  -V  "/home/marko/Brackets/test.xml" returned non-zero exit status 1

Thanks for your time and help!
Marko

**Comment by bobstayton** [comment]
Hello Marko,
This is not the appropriate place to report this problem. This list is for issues regarding DocBook schemas, and this is an application problem. I suggest you report this on the docbook-apps mailing list, where you will find users of asciidoc who might be able to help you.  You can subscribe to that mailing list here:
https://www.oasis-open.org/mlmanage/

**Comment by greguric** [comment]
Thank you Bob. Will do as suggested!

Marko
