### ISSUE TITLE
refentry not allowed in chapter

### ISSUE THREAD

**Issue by fekete-robert** [docbook/docbook#80]
Hi, 

the Docbook Reference Guide (http://tdg.docbook.org/tdg/5.1/refentry.html) mentions that chapters can contain refentry children. However, it seems that the RNG schema marks this as invalid (tested with version 5.1b7).

**Comment by ndw** [comment]
Can you post a sample? Chapter does allow refentry, but you can't mix refentry elements with other kinds of sections, for example.

**Comment by fekete-robert** [comment]
Hi Norman, 
Thank you for the swift response. I misunderstood the schema, and for some reason I thought that refentries are permitted after other kind of elements. I'll just wrap the refentry in a section. 

Thanks for your help!
