### ISSUE TITLE
Add stage direction markup to Publishers schema

### ISSUE THREAD

**Issue by shudson310** [docbook/docbook#81]
There is no support within DocBook Publishers for the semantic markup of stage directions. I'd like to propose the addition of two elements both allowing the standard set of inlines. The first would be a direction (or other suitable name) element, used to provide block level stage directions (between the speeches, etc) and the other would be inlinedirection (or...) to allow for inline stage direction markup.
The following shows the need for an inline direction element:
THE FLOWER GIRL [picking up her scattered flowers and replacing them in
the basket] There's menners f' yer! Te-oo banches o voylets trod into
the mad. [She sits down on the plinth of the column, sorting her
flowers, on the lady's right. She is not at all an attractive person.
She is perhaps eighteen, perhaps twenty, hardly older. She wears a
little sailor hat of black straw that has long been exposed to the dust
and soot of London and has seldom if ever been brushed. Her hair needs
washing rather badly: its mousy color can hardly be natural. She wears
a shoddy black coat that reaches nearly to her knees and is shaped to
her waist. She has a brown skirt with a coarse apron. Her boots are
much the worse for wear. She is no doubt as clean as she can afford to
be; but compared to the ladies she is very dirty. Her features are no
worse than theirs; but their condition leaves something to be desired;
and she needs the services of a dentist].
(from Pygmalion)
Suggested grammar (as RelaxNG compact)
# A stage direction.
db.direction.attlist = db.common.attributes
db.direction.content = (db.para+)
db.direction = element db:direction {db.direction.attlist, db.direction.content }
# inline stage direction.
db.inlinedirection.attlist = db.common.attributes
db.inlinedirection.content = (db.all.inlines+)
db.inlinedirection = element db:inlinedirection {db.inlinedirection.attlist, db.inlinedirection.content }

Propose to rename this as <stagedir> rather than <direction> for clarity. Direction could mistakenly confuse things with translation. 

Accepted for Publishers 1.1, but elements will be:
stagedir
inlinestagedir

**Comment by kosek** [comment]
This seems already implemented in 72f5acc92246eeb228552dd7a449fade1fdc4ac0
