### ISSUE TITLE
Add admonitions to Publishers

### ISSUE THREAD

**Issue by shudson310** [docbook/docbook#82]
The admonitions group was removed from DocBook Publishers. Recently, I've been working with vocational textbook publishers who use admonitions fairly extensively. If there is no strong reason for excluding them, perhaps they should be allowed to avoid the workarounds that have been required so far (using sidebars with role attributes)

Accepted in April SC meeting. (4/2012)

**Comment by kosek** [comment]
This seems already implemented in 72f5acc92246eeb228552dd7a449fade1fdc4ac0
