### ISSUE TITLE
Replacement for "annotation" element in Publishers schema

### ISSUE THREAD

**Issue by shudson310** [docbook/docbook#85]
I am currently using the "annotation" element within a book/info for any additional text on the imprint page, such as the description of photos on the front cover, and details about the type used in the book or the printer. I not that the annotation element is to be removed from the Publishers Schema. Would the Working Group consider introducing a new element (eg "imprint") for this miscellaneous information - there does not seem to be another suitable element that can be used as a child of info/.

Created by David Gardiner 6/2011

Would bibliomisc or bibliosource be more appropriate than annotation? Also, the publishers schema includes the full Dublin Core metadata attributes, which might also work?

**Comment by kosek** [comment]
It seems that this requirement can be easily solved by using cover element: https://tdg.docbook.org/tdg/5.2/cover.html

**Comment by shudson310** [comment]
Agreed. Recommend adding cover to the Publishers schema to meet this requirement.

**Comment by kosek** [comment]
Cover is already part of Publishers 5.2 so I'm closing this issue.
