### ISSUE TITLE
 linegroup and blockquote elements

### ISSUE THREAD

**Issue by shudson310** [docbook/docbook#86]
I'd like consideration given to allowing the <line/> element within <blockquote/> when <blockquote/> is a child of <linegroup/>.
<blockquote/> is allowed as a child of <linegroup/>, but <line/> cannot be wrapped by <blockquote/>
Presently the only way to wrap <line/> within <blockquote/> is to do so, on less I'm missing something, is as follows:
<blockquote>
<drama>
<linegroup>
<line></line>
<line></line>
</linegroup>
</drama>
</blockquote>
While I'm requesting this I suspect the problem will be what <blockquote/> already allows as its' children.
Thanks for considering.

PCThoms

**Comment by shudson310** [comment]
Further examples and use cases are needed. Please provide additional details for how you want this to work.

**Comment by shudson310** [comment]
PCThoms - 2013-03-18
I am working with legacy documents. In particular Shakespeare's plays.
The following is from the Tempest.

<bridgehead role="right">Sings in GONZALO’s ear.</bridgehead>
<linegroup> <speaker>GONZALO</speaker>
<line role="indent.5"><emphasis role="italic">While you here do snoring lie,</emphasis></line>
<line role="indent.5"><emphasis role="italic">Open-eyed Conspiracy</emphasis></line>
<line role="indent.5"><emphasis role="italic">His time doth take.</emphasis></line>
<line role="indent.5"><emphasis role="italic">If of life you keep a care,</emphasis></line>
<line role="indent.5"><emphasis role="italic">Shake of slumber and beware:</emphasis></line>
<line role="indent.5"><emphasis role="italic">Awake! awake!</emphasis></line>
</linegroup>

<bridgehead role="right">Sings in GONZALO’s ear.</bridgehead>
<linegroup> <speaker>GONZALO</speaker>
<blockquote>
<line><emphasis role="italic">While you here do snoring lie,</emphasis></line>
<line><emphasis role="italic">Open-eyed Conspiracy</emphasis></line>
<line><emphasis role="italic">His time doth take.</emphasis></line>
<line><emphasis role="italic">If of life you keep a care,</emphasis></line>
<line><emphasis role="italic">Shake of slumber and beware:</emphasis></line>
<line><emphasis role="italic">Awake! awake!</emphasis></line>
</blockquote>
</linegroup>
(This from is from page 33 of the edition we are using.)
There are numerous other times when allowing <line/> within <blockquote/> would be efficient.
Presently the most efficient way to do this is as follows:
<blockquote>
<drama>
<line></line>
</drama>
</blockquote>
We are able to work about this, as per above.

**Comment by shudson310** [comment]
Richard Hamilton - 2013-03-28
Is the only reason for using blockquote because you need to indent the text?
If so, then I don't think changing the schema is the best way to solve this problem. Here are two other possibilities:
1) If all lines within all linegroups need to be indented, then it would be best to adjust your stylesheets to automatically supply the indentation. That way, you wouldn't need the role attribute at all.
2) if all lines within only some linegroups need to be indented, then you could put the role on linegroup instead of on each line, and adjust the stylesheets to process that role for all lines within the group, so you don't need to put the role attribute on each line.
Either way, it looks like the reason for having blockquote is strictly tied to the rendering. If that's the case, then it would be better to modify the output stylesheets instead of using another element. There's one other place where you might consider a stylesheet change. If all lines need to be in italics, it would be better to set up the stylesheets to put all lines in italics, rather than have to wrap each line with the emphasis element.
If there's another reason for using blockquote that is related to the meaning of the lines within a linegroup, then can you explain further so we can see if it makes sense to add this capability?

**Comment by shudson310** [comment]
PCThoms - 2013-04-01
I'm working on a Shakespeare project which calls for <blockquote/> like use within a <linegroup/> at various places. As per the following:
<drama>
<linegroup><speaker></speaker>
<line>Text.</line>
<blockquote>
<line>Song.</line>
</blockquote>
<line>Text.</line>
</linegroup>
</drama>
While <blockquote/> may appear <linegroup/>, <line/> is not valid within <blockquote/> in this context.
However, the following is valid:
<drama>
<blockquote>
<drama>
<linegroup>
<line></line>
<line></line>
</linegroup>
</drama>
</blockquote>
</drama>
This is a cumbersome, but we can work with this.
Hope this is clear and helpful.

**Comment by shudson310** [comment]
Richard Hamilton - 2013-04-02
I see what you are trying to do, and I can see why it would be useful to group some lines that represent a song or poem in the middle of a linegroup. I'll let the technical sub-committee know what you're asking for and see if they think this is the best way to represent this kind of thing or if they have another suggestion.

**Comment by shudson310** [comment]
PCThoms - 2013-04-05
Hi Richard
The following can work without any changes.
<drama>
<linegroup><speaker></speaker>
<line>Text.</line>
<line role="blockquote">Song.</line>
<line>Text.</line>
</linegroup>
</drama>
If anyone has a better solution I'd be glad to know it.
With thanks

**Comment by kosek** [comment]
Hi @shudson310 it seems that GitHub stripped markup from code samples.

**Comment by shudson310** [comment]
See the thread here: https://lists.oasis-open.org/archives/docbook-publishers/201304/msg00007.html

I think the linegroup provides the sufficient structure here.

**Comment by kosek** [comment]
So if I understand it correctly no schema change is needed for this and issue can be closed?

**Comment by shudson310** [comment]
Correct. Closing the issue.
