### ISSUE TITLE
DB 5.0: @name -> title change not published on docbook.org

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#88]
## Problem

In one of the former DocBook 5.0 releases, embedded Schematron rules contained a `name` attribute although a `s:title` element is needed. For this reason, #2 was opened and fixed.

However, if you download the DocBook 5.0 RNG file from http://docbook.org/xml/5.0/rng/docbook.rng this is still the case. The same applies for the RNC file.

## Solution
Release DocBook 5.0 with correct Schematron rules. ;-)

**Comment by shudson310** [comment]
Added to 5.0.1
