### ISSUE TITLE
Diff between doc of resource element and Assembly schema

### ISSUE THREAD

**Issue by tomschr** [docbook/docbook#93]
In the [TDG 5.2](http://tdg.docbook.org/tdg/5.2/ch06.html#ex-book) page about assemblies, you can find this example:

```xml
<resource xml:id="full-toc">
  <toc/>
  <toc role="figures"/>
  <toc role="tables"/>
  <toc role="procedures"/>
</resource>
<!-- ... rest omitted ... -->
```

However, when you try to use that example with the latest DocBook schema (http://docbook.org/xml/5.2b02/rng/assembly.rnc), it gives a validation error.

The `resource` element has this content model:

```rnc
db.resource =
    ## Identifies an object managed within the assembly
    element resource {
      db.resource.attlist, db.resource.href.attribute, db.description*
    }
```

The `toc` element isn't allowed. Either the schema is incomplete or the documentation is invalid. 😉 Please adjust.

**Comment by ndw** [comment]
I believe this got fixed.
