### ISSUE TITLE
Allow iframe and embed tags

### ISSUE THREAD

**Issue by peterfleck** [docbook/docbook#95]
Propose adding iframe and embed tags.

My specific use case is a video datasource that only allows iframe embedding, using Docbook's mediaobject/videoobject doesn't work.

Maybe have some kind of correlation with what schema.org have done with mediaobject -
 http://schema.org/MediaObject

**Comment by kosek** [comment]
You can modify DocBook XSLT stylesheets to generate any HTML markup (be it HTML5 video element, embed for Flash or iframe or whatever) from DocBook videoobject element. So I don't think there is a need to change DocBook schema.

**Comment by peterfleck** [comment]
Thanks @kosek. I hadn't realised that was possible. That will be v. helpful.
