### ISSUE TITLE
missing bibliography in glossary

### ISSUE THREAD

**Issue by denis-stepanov** [docbook/docbook#97]
Docbook XSD, as well as documentation, allow for using bibliography inside the glossary element. However, when I try this on a glossary document (having glossary as top level tag), no bibliography is generated in xhtml. The citation links are generated though, but point to nowhere. I had to patch the 1.79.2 XSL like this in order to get the bibliography generated:

```
--- xhtml/glossary.xsl.orig     2017-12-07 13:47:43.931306100 +0100
+++ xhtml/glossary.xsl  2017-12-07 13:57:42.652172200 +0100
@@ -73,6 +73,9 @@
       </xsl:otherwise>
     </xsl:choose>
 
+       <!-- DSV20171207: produce glossary bibliography -->
+       <xsl:apply-templates select="d:bibliography"/>
+
     <xsl:if test="not(parent::d:article)">
       <xsl:call-template name="process.footnotes"/>
     </xsl:if>

```
Could you please check if this is a bug or I am missing something?..

**Comment by bobstayton** [comment]
Thank you for reporting this.  However, this is a stylesheet issue, and this repository is for issues with the DocBook schemas.  In order for this to be resolved by the stylesheet team, please report it on the issues list for the stylesheet repository at https://github.com/docbook/xslt10-stylesheets.  If I knew how to transfer an issue from one repo to another I would, but I don't.  8^)
