### ISSUE TITLE
recursive glossentry causes XSL exception

### ISSUE THREAD

**Issue by denis-stepanov** [docbook/docbook#98]
I have the following entry in a glossary:

```
		<glossentry xml:id="GNU">
			<glossterm>
				<glossterm linkend="GNU">GNU</glossterm>'s Not <glossterm linkend="UNIX">UNIX</glossterm>
			</glossterm>
			<acronym>GNU</acronym>
			<glossdef>
				<para/>
				<remark>This is a recursive acronym</remark>
			</glossdef>
		</glossentry>

```
Processing this with 1.79.2 xhtml stylesheet using xsltproc gives "Segmentation fault (core dumped)". Saxon reports a looping stylesheet and aborts.

With an older version of docbook (1.77.1) the recursive entry is processed correctly.

**Comment by shudson310** [comment]
Thank you for reporting this. However, this is a stylesheet issue, and this repository is for issues with the DocBook schemas. In order for this to be resolved by the stylesheet team, please report it on the issues list for the stylesheet repository at https://github.com/docbook/xslt10-stylesheets. If I knew how to transfer an issue from one repo to another I would, but I don't. 8^)
